// port-lint: source src/values/types/function.rs
package io.github.kotlinmania.starlark_kotlin.values.types

/*
 * Copyright 2018 The Starlark in Rust Authors.
 * Copyright (c) Facebook, Inc. and its affiliates.
 * Copyright (c) 2025 Sydney Renee, The Solace Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Function types, including native functions and `object.member` functions.

import io.github.kotlinmania.starlark_kotlin.docs.DocItem
import io.github.kotlinmania.starlark_kotlin.docs.DocMember
import io.github.kotlinmania.starlark_kotlin.docs.DocProperty
import io.github.kotlinmania.starlark_kotlin.docs.DocString
import io.github.kotlinmania.starlark_kotlin.docs.DocStringKind
import io.github.kotlinmania.starlark_kotlin.docs.fromDocstring
import io.github.kotlinmania.starlark_kotlin.typing.Ty
import io.github.kotlinmania.starlark_kotlin.typing.TyBasic
import io.github.kotlinmania.starlark_kotlin.typing.arc_ty.ArcTy
import io.github.kotlinmania.starlark_kotlin.values.AllocFrozenValue
import io.github.kotlinmania.starlark_kotlin.values.AllocValue
import io.github.kotlinmania.starlark_kotlin.values.Freeze
import io.github.kotlinmania.starlark_kotlin.values.Freezer
import io.github.kotlinmania.starlark_kotlin.values.FrozenHeap
import io.github.kotlinmania.starlark_kotlin.values.FrozenValue
import io.github.kotlinmania.starlark_kotlin.values.StarlarkValue
import io.github.kotlinmania.starlark_kotlin.values.ValueError
import io.github.kotlinmania.starlark_kotlin.values.types.ellipsis.Ellipsis
import io.github.kotlinmania.starlark_kotlin.values.typing.type_compiled.TypeCompiled
import io.github.kotlinmania.starlark_kotlin.values.typing.TyTuple
import io.github.kotlinmania.starlark_kotlin.values.layout.ValueLike
import io.github.kotlinmania.starlark_kotlin.eval.runtime.Evaluator
import io.github.kotlinmania.starlark_kotlin.eval.runtime.Arguments
import io.github.kotlinmania.starlark_kotlin.values.StarlarkTypeRepr
import io.github.kotlinmania.starlark_kotlin.eval.runtime.params.spec.ParametersSpec
import io.github.kotlinmania.starlark_kotlin.values.layout.heap.Heap
import io.github.kotlinmania.starlark_kotlin.values.layout.Value
import io.github.kotlinmania.starlark_kotlin.values.toValue
import io.github.kotlinmania.starlark_kotlin.values.typing.type_compiled.typeSetOf
import io.github.kotlinmania.starlark_kotlin.values.typing.type_compiled.typeListOf
import io.github.kotlinmania.starlark_kotlin.values.typing.type_compiled.typeDictOf
import io.github.kotlinmania.starlark_kotlin.values.typing.type_compiled.fromTy
import io.github.kotlinmania.starlark_kotlin.values.typing.type_compiled.asTy
import io.github.kotlinmania.starlark_kotlin.values.documentation
import io.github.kotlinmania.starlark_kotlin.values.freeze_error.FreezeResult
import io.github.kotlinmania.starlark_kotlin.values.layout.FrozenValueTyped
import io.github.kotlinmania.starlark_kotlin.values.layout.avalues.simple.allocSimple
import io.github.kotlinmania.starlark_kotlin.typing.ArcTy

// #[derive(Debug, thiserror::Error)]
// enum FunctionError
internal sealed class FunctionError(message: String) : Exception(message) {
    // #[error("`tuple[]` is implemented only for `tuple[T, ...]`")]
    // TupleOnlyEllipsis
    class TupleOnlyEllipsis : FunctionError("`tuple[]` is implemented only for `tuple[T, ...]`")
}

/// Return value of `type(any function)`.
// pub const FUNCTION_TYPE: &str = "function"
const val FUNCTION_TYPE: String = "function"

/// Marker trait for function types.
// pub(crate) enum StarlarkFunction {}
internal object StarlarkFunction : StarlarkTypeRepr {
    // impl StarlarkTypeRepr for StarlarkFunction
    // fn starlark_type_repr() -> Ty
    override fun starlarkTypeRepr(): Ty {
        return Ty.anyCallable()
    }
}

// #[derive(Debug, Allocative, Clone, Copy, Dupe)]
// pub enum SpecialBuiltinFunction
enum class SpecialBuiltinFunction {
    List,
    Dict,
    Tuple,
    Set,
}

/// Type alias for functions generated by macro
// pub type NativeFuncFn = ...
typealias NativeFuncFn = (eval: Evaluator, sig: ParametersSpec<FrozenValue>, args: Arguments) -> Result<Value>

/// Storage for a `NativeFuncFn` and the parameters spec needed to call it
// #[derive(Debug, ProvidesStaticType, Allocative)]
// pub(crate) struct NativeFunc
internal class NativeFunc(
    val function: NativeFuncFn,
    val parametersSpec: ParametersSpec<FrozenValue>,
) {
    // pub(crate) fn invoke<'v>(&self, eval: &mut Evaluator<'v, '_, '_>, args: &Arguments<'v, '_>) -> crate::Result<Value<'v>>
    fun invoke(eval: Evaluator, args: Arguments): Result<Value> {
        return function(eval, parametersSpec, args)
    }
}

/// Starlark representation of native (Rust) functions.
///
/// Almost always created with `#[starlark_module]`.
// #[derive(Derivative, ProvidesStaticType, Display, NoSerialize, Allocative)]
// pub(crate) struct NativeFunction
internal class NativeFunction(
    val function: NativeFunc,
    val name: String,
    /// `.type` attribute and a type when this function is used in type expression.
    val asType: Ty?,
    val ty: Ty,
    /// Safe to evaluate speculatively.
    val speculativeExecSafe: Boolean,
    val docs: DocItem,
    val specialBuiltinFunction: SpecialBuiltinFunction?,
) : StarlarkValue, AllocFrozenValue, AllocValue {

    // #[starlark_value(type = FUNCTION_TYPE)]
    override val TYPE: String get() = FUNCTION_TYPE

    override fun toString(): String = name

    // impl AllocFrozenValue for NativeFunction
    override fun allocFrozenValue(heap: FrozenHeap): FrozenValue {
        return heap.allocSimple(this)
    }

    // impl AllocValue for NativeFunction
    override fun allocValue(heap: Heap): Value {
        return heap.allocSimple(this)
    }

    // fn invoke(&self, _me: Value<'v>, args: &Arguments<'v, '_>, eval: &mut Evaluator<'v, '_, '_>) -> crate::Result<Value<'v>>
    override fun invoke(me: Value, args: Arguments, eval: Evaluator): Result<Value> {
        return function.invoke(eval, args)
    }

    // fn get_attr(&self, attribute: &str, heap: Heap<'v>) -> Option<Value<'v>>
    override fun getAttr(attribute: String, heap: Heap): Value? {
        val s = asType?.asName()
        if (s != null && attribute == "type") {
            return heap.alloc(s)
        }
        return null
    }

    // fn eval_type(&self) -> Option<Ty>
    fun evalType(): Ty? = asType

    // fn has_attr(&self, _attribute: &str, _heap: Heap<'v>) -> bool
    override fun hasAttr(attribute: String, heap: Heap): Boolean {
        return false
    }

    // fn dir_attr(&self) -> Vec<String>
    override fun dirAttr(): kotlin.collections.List<String> {
        return if (asType != null) {
            listOf("type")
        } else {
            emptyList()
        }
    }

    // fn documentation(&self) -> DocItem
    override fun documentation(): DocItem = docs

    // fn typechecker_ty(&self) -> Option<Ty>
    fun typecheckerTy(): Ty? = ty

    // fn at(&self, index: Value<'v>, heap: Heap<'v>) -> crate::Result<Value<'v>>
    override fun at(index: Value, heap: Heap): Result<Value> {
        return when (specialBuiltinFunction) {
            SpecialBuiltinFunction.List -> {
                val idx = runCatching { TypeCompiled.new(index, heap) }.getOrElse { return Result.failure(it) }
                Result.success(TypeCompiled.typeListOf(idx, heap).toInner())
            }
            SpecialBuiltinFunction.Set -> {
                val idx = runCatching { TypeCompiled.new(index, heap) }.getOrElse { return Result.failure(it) }
                Result.success(TypeCompiled.typeSetOf(idx, heap).toInner())
            }
            else -> ValueError.unsupported(this, "[]")
        }
    }

    // fn at2(&self, index0: Value<'v>, index1: Value<'v>, heap: Heap<'v>, _private: Private) -> crate::Result<Value<'v>>
    fun at2(index0: Value, index1: Value, heap: Heap): Result<Value> {
        return when (specialBuiltinFunction) {
            SpecialBuiltinFunction.Dict -> {
                val idx0 = runCatching { TypeCompiled.new(index0, heap) }.getOrElse { return Result.failure(it) }
                val idx1 = runCatching { TypeCompiled.new(index1, heap) }.getOrElse { return Result.failure(it) }
                Result.success(TypeCompiled.typeDictOf(idx0, idx1, heap).toInner())
            }
            SpecialBuiltinFunction.Tuple -> {
                val item = runCatching { TypeCompiled.new(index0, heap) }.getOrElse { return Result.failure(it) }
                if (index1.downcastRef<Ellipsis>() != null) {
                    Result.success(
                        TypeCompiled.fromTy(
                            Ty.basic(TyBasic.Tuple(TyTuple.Of(ArcTy(item.asTy())))),
                            heap,
                        ).toInner(),
                    )
                } else {
                    Result.failure(FunctionError.TupleOnlyEllipsis())
                }
            }
            else -> ValueError.unsupported(this, "[,]")
        }
    }
}

/// Type alias for functions generated by macro
// pub type NativeMethFn = ...
typealias NativeMethFn = (eval: Evaluator, thisValue: Value, sig: ParametersSpec<FrozenValue>, args: Arguments) -> Result<Value>

/// Storage for a `NativeMethFn` and the parameters spec needed to call it
// #[derive(Debug, ProvidesStaticType, Allocative)]
// pub(crate) struct NativeMeth
internal class NativeMeth(
    val function: NativeMethFn,
    val parametersSpec: ParametersSpec<FrozenValue>,
) {
    // pub(crate) fn invoke<'v>(&self, eval: &mut Evaluator<'v, '_, '_>, this: Value<'v>, args: &Arguments<'v, '_>) -> crate::Result<Value<'v>>
    fun invoke(eval: Evaluator, thisValue: Value, args: Arguments): Result<Value> {
        return function(eval, thisValue, parametersSpec, args)
    }
}

// #[derive(Derivative, Display, NoSerialize, ProvidesStaticType, Allocative)]
// pub(crate) struct NativeMethod
internal class NativeMethod(
    val function: NativeMeth,
    val name: String,
    val ty: Ty,
    /// Safe to evaluate speculatively.
    val speculativeExecSafe: Boolean,
    val docs: DocItem,
) : StarlarkValue {
    // starlark_simple_value!(NativeMethod)

    // #[starlark_value(type = "native_method")]
    override val TYPE: String get() = "native_method"

    override fun toString(): String = name

    // fn documentation(&self) -> DocItem
    override fun documentation(): DocItem = docs

    // fn typechecker_ty(&self) -> Option<Ty>
    fun typecheckerTy(): Ty? = ty
}

/// Used by the `#[starlark(attribute)]` tag of `#[starlark_module]`
/// to define a function that pretends to be an attribute.
// #[derive(Derivative, Display, NoSerialize, ProvidesStaticType, Allocative)]
// pub(crate) struct NativeAttribute
internal class NativeAttribute(
    /// Safe to evaluate speculatively.
    val speculativeExecSafe: Boolean,
    val docstring: String?,
    val typ: Ty,
    val data: FrozenValue?,
    val callable: (data: FrozenValue?, thisValue: Value, heap: Heap) -> Result<Value>,
) : StarlarkValue {
    // starlark_simple_value!(NativeAttribute)

    // #[starlark_value(type = "attribute")]
    override val TYPE: String get() = "attribute"

    override fun toString(): String = "Attribute"

    // pub(crate) fn invoke<'v>(&self, this: Value<'v>, heap: Heap<'v>) -> crate::Result<Value<'v>>
    fun invoke(thisValue: Value, heap: Heap): Result<Value> {
        return callable(data, thisValue, heap)
    }

    // fn documentation(&self) -> DocItem
    override fun documentation(): DocItem {
        val ds = docstring?.let { DocString.fromDocstring(DocStringKind.Rust, it) }
        val typ = this.typ
        return DocItem.Member(DocMember.Property(DocProperty(docs = ds, typ = typ)))
    }
}

/// A wrapper for a method with a self object already bound.
// #[derive(Clone, Debug, Trace, Coerce, Display, Freeze, NoSerialize, ProvidesStaticType, Allocative)]
// pub(crate) struct BoundMethodGen<V: ValueLifetimeless>
internal class BoundMethodGen<V>(
    val method: FrozenValueTyped<NativeMethod>,
    val thisValue: V,
) : StarlarkValue, Freeze<BoundMethodGen<FrozenValue>> {

    // starlark_complex_value!(pub(crate) BoundMethod)
    // Generated type aliases:
    //   pub(crate) type BoundMethod<'v> = BoundMethodGen<Value<'v>>;
    //   pub(crate) type FrozenBoundMethod = BoundMethodGen<FrozenValue>;

    // #[starlark_value(type = FUNCTION_TYPE)]
    override val TYPE: String get() = FUNCTION_TYPE

    override fun toString(): String = method.toString()

    /// Create a new BoundMethod. Given the expression `object.function`,
    /// the first argument would be `object`, and the second would be `getattr(object, "function")`.
    // pub(crate) fn new(this: V, method: FrozenValueTyped<'static, NativeMethod>) -> Self

    /** Convert thisValue to a Value, regardless of whether V is Value or FrozenValue. */
    private fun thisAsValue(): Value = when (val v = thisValue) {
        is Value -> v
        is FrozenValue -> v.toValue()
        is ValueLike -> v.toValue()
        else -> error("BoundMethodGen: unexpected thisValue type: ${v?.let { it::class }}")
    }

    // fn invoke(&self, _me: Value<'v>, args: &Arguments<'v, '_>, eval: &mut Evaluator<'v, '_, '_>) -> crate::Result<Value<'v>>
    override fun invoke(me: Value, args: Arguments, eval: Evaluator): Result<Value> {
        return method.asRef().function.invoke(eval, thisAsValue(), args)
    }

    // fn documentation(&self) -> DocItem
    override fun documentation(): DocItem = method.asRef().documentation()

    // impl Freeze for BoundMethodGen<V>
    override fun freeze(freezer: Freezer): FreezeResult<BoundMethodGen<FrozenValue>> {
        val frozenThis = freezer.freeze(thisAsValue()).getOrElse { return Result.failure(it) }
        return Result.success(BoundMethodGen(method, frozenThis))
    }
}

// starlark_complex_value!(pub(crate) BoundMethod) generates:
internal typealias BoundMethod = BoundMethodGen<Value>
internal typealias FrozenBoundMethod = BoundMethodGen<FrozenValue>
