// port-lint: source src/values/types/record/field.rs
package io.github.kotlinmania.starlark.values.types.record

/*
 * Copyright 2019 The Starlark in Rust Authors.
 * Copyright (c) Facebook, Inc. and its affiliates.
 * Copyright (c) 2025 Sydney Renee, The Solace Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import io.github.kotlinmania.starlark.collections.StarlarkHasher
import io.github.kotlinmania.starlark.typing.Ty
import io.github.kotlinmania.starlark.typing.TyStarlarkValue
import io.github.kotlinmania.starlark.values.ComplexValue
import io.github.kotlinmania.starlark.values.Freeze
import io.github.kotlinmania.starlark.values.Trace
import io.github.kotlinmania.starlark.values.layout.Freezer
import io.github.kotlinmania.starlark.values.layout.Value
import io.github.kotlinmania.starlark.values.layout.heap.Tracer
import io.github.kotlinmania.starlark.values.layout.heap.ValueHolder
import io.github.kotlinmania.starlark.values.typing.typecompiled.TypeCompiled

/**
 * The result of `field()`.
 */
// Kotlin: single class, no lifetime parameterization.
class Field internal constructor(
    internal var typ: TypeCompiled,
    internal var default: Value?,
) : ComplexValue,
    Freeze<Field>,
    Trace {
    companion object {
        internal fun new(typ: TypeCompiled, default: Value?): Field = Field(typ = typ, default = default)

        // Downcast a value to a Field (generated by starlark_complex_value! macro in Rust).
        internal fun fromValue(value: Value): Field? =
            value.downcastRef()
    }

    override fun freeze(freezer: Freezer): Result<Field> {
        val frozenTyp = typ.toFrozen(freezer.frozenHeap())
        val frozenDefault =
            if (default != null) {
                freezer.freeze(default!!).getOrElse { return Result.failure(it) }
            } else {
                null
            }
        return Result.success(Field(frozenTyp, frozenDefault?.toValue()))
    }

    override fun trace(tracer: Tracer) {
        typ.trace(tracer)
        if (default != null) {
            val holder = ValueHolder(default!!)
            tracer.trace(holder)
            default = holder.value
        }
    }

    internal fun ty(): Ty = typ.asTy()

    override val TYPE: String get() = "field"

    override fun writeHash(hasher: StarlarkHasher): Result<Unit> {
        typ.writeHash(hasher).getOrElse { return Result.failure(it) }
        val def = default
        hasher.writeU8(if (def != null) 1u else 0u)
        if (def != null) {
            def.writeHash(hasher).getOrElse { return Result.failure(it) }
        }
        return Result.success(Unit)
    }

    override fun typecheckerTy(): Ty = Ty.starlarkValue(TyStarlarkValue.new("field"))

    override fun toString(): String =
        buildString {
            append("field(")
            append(typ)
            if (default != null) {
                append(", ")
                append(default)
            }
            append(")")
        }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Field) return false
        return typ == other.typ && default == other.default
    }

    override fun hashCode(): Int {
        var result = typ.hashCode()
        result = 31 * result + (default?.hashCode() ?: 0)
        return result
    }
}
