// port-lint: source src/values/types/function.rs
package io.github.kotlinmania.starlark.values.types

/*
 * Copyright 2018 The Starlark in Rust Authors.
 * Copyright (c) Facebook, Inc. and its affiliates.
 * Copyright (c) 2025 Sydney Renee, The Solace Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not import this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** Function types, including native functions and `object.member` functions. */

import io.github.kotlinmania.starlark.docs.DocItem
import io.github.kotlinmania.starlark.docs.DocMember
import io.github.kotlinmania.starlark.docs.DocProperty
import io.github.kotlinmania.starlark.docs.DocString
import io.github.kotlinmania.starlark.docs.DocStringKind
import io.github.kotlinmania.starlark.docs.fromDocstring
import io.github.kotlinmania.starlark.typing.ArcTy
import io.github.kotlinmania.starlark.typing.Ty
import io.github.kotlinmania.starlark.typing.TyBasic
import io.github.kotlinmania.starlark.typing.TyTuple
import io.github.kotlinmania.starlark.values.AllocFrozenValue
import io.github.kotlinmania.starlark.values.AllocValue
import io.github.kotlinmania.starlark.values.ComplexValue
import io.github.kotlinmania.starlark.values.Freeze
import io.github.kotlinmania.starlark.values.layout.Freezer
import io.github.kotlinmania.starlark.values.layout.heap.FrozenHeap
import io.github.kotlinmania.starlark.values.layout.FrozenValue
import io.github.kotlinmania.starlark.values.StarlarkValue
import io.github.kotlinmania.starlark.values.StarlarkTypeRepr
import io.github.kotlinmania.starlark.values.ValueError
import io.github.kotlinmania.starlark.values.toValue
import io.github.kotlinmania.starlark.values.types.ellipsis.Ellipsis
import io.github.kotlinmania.starlark.values.typing.typecompiled.TypeCompiled
import io.github.kotlinmania.starlark.values.layout.ValueLike
import io.github.kotlinmania.starlark.eval.runtime.Evaluator
import io.github.kotlinmania.starlark.eval.runtime.Arguments
import io.github.kotlinmania.starlark.eval.runtime.params.spec.ParametersSpec
import io.github.kotlinmania.starlark.values.layout.heap.Heap
import io.github.kotlinmania.starlark.values.layout.Value
import io.github.kotlinmania.starlark.values.layout.FrozenValueTyped
import io.github.kotlinmania.starlark.values.layout.avalues.simple.allocSimple

internal sealed class FunctionError(message: String) : Exception(message) {
    // TupleOnlyEllipsis
    class TupleOnlyEllipsis : FunctionError("`tuple[]` is implemented only for `tuple[T, ...]`")
}

/** Return value of `type(any function)`. */
const val FUNCTION_TYPE: String = "function"

/** Marker trait for function types. */
internal object StarlarkFunction : StarlarkTypeRepr {
    override fun starlarkTypeRepr(): Ty {
        return Ty.anyCallable()
    }
}

enum class SpecialBuiltinFunction {
    List,
    Dict,
    Tuple,
    Set,
}

/** Type alias for functions generated by macro */
fun interface NativeFuncFn {
    operator fun invoke(eval: Evaluator, sig: ParametersSpec<FrozenValue>, args: Arguments): Result<Value>
}

/** Storage for a `NativeFuncFn` and the parameters spec needed to call it */
internal class NativeFunc(
    val function: NativeFuncFn,
    val parametersSpec: ParametersSpec<FrozenValue>,
) {
    fun invoke(eval: Evaluator, args: Arguments): Result<Value> {
        return function(eval, parametersSpec, args)
    }
}

/**
 * Starlark representation of native (Rust) functions.
 *
 */
internal class NativeFunction(
    val function: NativeFunc,
    val name: String,
    /** `.type` attribute and a type when this function is used in type expression. */
    val asType: Ty?,
    val ty: Ty,
    /** Safe to evaluate speculatively. */
    val speculativeExecSafe: Boolean,
    val docs: DocItem,
    val specialBuiltinFunction: SpecialBuiltinFunction?,
) : StarlarkValue, AllocFrozenValue, AllocValue {

    override val TYPE: String get() = FUNCTION_TYPE

    override fun starlarkTypeRepr(): Ty = getTypeStarlarkRepr()

    override fun toString(): String = name

    override fun allocFrozenValue(heap: FrozenHeap): FrozenValue {
        return heap.allocSimple(this)
    }

    override fun allocValue(heap: Heap): Value {
        return heap.allocSimple(this)
    }

    override fun invoke(_me: Value, args: Arguments, eval: Evaluator): Result<Value> {
        return function.invoke(eval, args)
    }

    override fun getAttr(attribute: String, heap: Heap): Value? {
        val s = asType?.asName()
        if (s != null && attribute == "type") {
            return heap.allocStr(s).toValue()
        }
        return null
    }

    override fun evalType(): Ty? = asType

    override fun hasAttr(_attribute: String, _heap: Heap): Boolean {
        return false
    }

    override fun dirAttr(): kotlin.collections.List<String> {
        return if (asType != null) {
            listOf("type")
        } else {
            emptyList()
        }
    }

    override fun documentation(): DocItem = docs

    override fun typecheckerTy(): Ty? = ty

    override fun at(index: Value, heap: Heap): Result<Value> {
        return when (specialBuiltinFunction) {
            SpecialBuiltinFunction.List -> {
                val idx = runCatching { TypeCompiled.new(index, heap) }.getOrElse { return Result.failure(it) }
                Result.success(TypeCompiled.typeListOf(idx, heap).toInner())
            }
            SpecialBuiltinFunction.Set -> {
                val idx = runCatching { TypeCompiled.new(index, heap) }.getOrElse { return Result.failure(it) }
                Result.success(TypeCompiled.typeSetOf(idx, heap).toInner())
            }
            else -> ValueError.unsupported(TYPE, "[]")
        }
    }

    override fun at2(index0: Value, index1: Value, heap: Heap): Result<Value> {
        return when (specialBuiltinFunction) {
            SpecialBuiltinFunction.Dict -> {
                val idx0 = runCatching { TypeCompiled.new(index0, heap) }.getOrElse { return Result.failure(it) }
                val idx1 = runCatching { TypeCompiled.new(index1, heap) }.getOrElse { return Result.failure(it) }
                Result.success(TypeCompiled.typeDictOf(idx0, idx1, heap).toInner())
            }
            SpecialBuiltinFunction.Tuple -> {
                val item = runCatching { TypeCompiled.new(index0, heap) }.getOrElse { return Result.failure(it) }
                if (index1.downcastRef<Ellipsis>() != null) {
                    Result.success(
                        TypeCompiled.fromTy(
                            Ty.basic(TyBasic.Tuple(TyTuple.Of(ArcTy.new(item.asTy())))),
                            heap,
                        ).toInner(),
                    )
                } else {
                    Result.failure(FunctionError.TupleOnlyEllipsis())
                }
            }
            else -> ValueError.unsupported(TYPE, "[,]")
        }
    }
}

/** Type alias for functions generated by macro */
fun interface NativeMethFn {
    operator fun invoke(eval: Evaluator, thisValue: Value, sig: ParametersSpec<FrozenValue>, args: Arguments): Result<Value>
}

/** Storage for a `NativeMethFn` and the parameters spec needed to call it */
internal class NativeMeth(
    val function: NativeMethFn,
    val parametersSpec: ParametersSpec<FrozenValue>,
) {
    fun invoke(eval: Evaluator, thisValue: Value, args: Arguments): Result<Value> {
        return function(eval, thisValue, parametersSpec, args)
    }
}

internal class NativeMethod(
    val function: NativeMeth,
    val name: String,
    val ty: Ty,
    /** Safe to evaluate speculatively. */
    val speculativeExecSafe: Boolean,
    val docs: DocItem,
) : StarlarkValue {

    override val TYPE: String get() = "native_method"

    override fun toString(): String = name

    override fun documentation(): DocItem = docs

    override fun typecheckerTy(): Ty? = ty
}

/**
 * to define a function that pretends to be an attribute.
 */
internal class NativeAttribute(
    /** Safe to evaluate speculatively. */
    val speculativeExecSafe: Boolean,
    val docstring: String?,
    val typ: Ty,
    val data: FrozenValue?,
    val callable: (data: FrozenValue?, thisValue: Value, heap: Heap) -> Result<Value>,
) : StarlarkValue {

    override val TYPE: String get() = "attribute"

    override fun toString(): String = "Attribute"

    fun invoke(thisValue: Value, heap: Heap): Result<Value> {
        return callable(data, thisValue, heap)
    }

    override fun documentation(): DocItem {
        val ds = docstring?.let { DocString.fromDocstring(DocStringKind.Rust, it) }
        val typ = this.typ
        return DocItem.Member(DocMember.Property(DocProperty(docs = ds, typ = typ)))
    }
}

/** A wrapper for a method with a self object already bound. */
internal class BoundMethodGen<V>(
    val method: FrozenValueTyped<NativeMethod>,
    val thisValue: V,
) : ComplexValue, Freeze<BoundMethodGen<FrozenValue>> {

    override val TYPE: String get() = FUNCTION_TYPE

    override fun toString(): String = method.toString()

    /**
     * Create a new BoundMethod. Given the expression `object.function`,
     * the first argument would be `object`, and the second would be `getattr(object, "function")`.
     */

    /** Convert thisValue to a Value, regardless of whether V is Value or FrozenValue. */
    private fun thisAsValue(): Value = when (val v = thisValue) {
        is Value -> v
        is FrozenValue -> v.toValue()
        is ValueLike<*> -> v.toValue()
        else -> error("BoundMethodGen: unexpected thisValue type: ${v?.let { it::class }}")
    }

    override fun invoke(_me: Value, args: Arguments, eval: Evaluator): Result<Value> {
        return method.asRef().function.invoke(eval, thisAsValue(), args)
    }

    override fun documentation(): DocItem = method.asRef().documentation()

    override fun freeze(freezer: Freezer): Result<BoundMethodGen<FrozenValue>> {
        val frozenThis = freezer.freeze(thisAsValue()).getOrElse { return Result.failure<BoundMethodGen<FrozenValue>>(it) }
        return Result.success(BoundMethodGen(method, frozenThis))
    }
}

