// port-lint: source src/values/types/list/value.rs
package io.github.kotlinmania.starlark.values.types.list

// Copyright 2018 The Starlark in Rust Authors.
// Copyright (c) Facebook, Inc. and its affiliates.
// Copyright (c) 2025 Sydney Renee, The Solace Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import io.github.kotlinmania.starlark.environment.Methods
import io.github.kotlinmania.starlark.environment.MethodsStatic
import io.github.kotlinmania.starlark.typing.Ty
import io.github.kotlinmania.starlark.values.AllocFrozenValue
import io.github.kotlinmania.starlark.values.AllocValue
import io.github.kotlinmania.starlark.values.StarlarkTypeRepr
import io.github.kotlinmania.starlark.values.StarlarkValue
import io.github.kotlinmania.starlark.values.ValueError
import io.github.kotlinmania.starlark.values.applySlice
import io.github.kotlinmania.starlark.values.compareSlice
import io.github.kotlinmania.starlark.values.convertIndex
import io.github.kotlinmania.starlark.values.equalsSlice
import io.github.kotlinmania.starlark.values.layout.FrozenValue
import io.github.kotlinmania.starlark.values.layout.Value
import io.github.kotlinmania.starlark.values.layout.avalues.AllocStaticSimple
import io.github.kotlinmania.starlark.values.layout.avalues.allocList
import io.github.kotlinmania.starlark.values.layout.avalues.allocListIter
import io.github.kotlinmania.starlark.values.layout.heap.FrozenHeap
import io.github.kotlinmania.starlark.values.layout.heap.Heap
import kotlin.math.max

/** Generic list container, parameterized on the data type. */
class ListGen<T>(
    val data: T,
) : StarlarkValue {
    override val TYPE: String get() = ListData.TYPE
    override val HAS_iterate: Boolean get() = true
    override val HAS_equals: Boolean get() = true

    override fun isSpecial(): Boolean = true

    override fun getMethods(): Methods? = listMethods()

    override fun toString(): String = data.toString()

    // StarlarkValue iteration overrides — delegate to ListLike data.
    // In Rust these are generated by the #[starlark_value] proc macro.

    override fun iterate(me: Value, heap: Heap): Result<Value> =
        Result.success((data as ListLike).newIter(me))

    override fun iterSizeHint(index: Int): Pair<Int, Int?> =
        (data as ListLike).iterSizeHint(index)

    override fun iterNext(index: Int, heap: Heap): Value? =
        (data as ListLike).iterNext(index)

    override fun iterStop() =
        (data as ListLike).iterStop()

    override fun length(): Result<Int> =
        Result.success((data as ListLike).content().size)

    override fun toBool(): Boolean =
        (data as ListLike).content().isNotEmpty()

    override fun collectRepr(collector: StringBuilder) {
        collector.append("[")
        var first = true
        for (v in (data as ListLike).content()) {
            if (!first) collector.append(", ")
            first = false
            v.collectRepr(collector)
        }
        collector.append("]")
    }

    override fun collectReprCycle(collector: StringBuilder) {
        collector.append("[...]")
    }

    private fun listLike(): ListLike = data as ListLike

    override fun equals(other: Value): Result<Boolean> {
        val otherRef = ListRef.fromValue(other) ?: return Result.success(false)
        return equalsSlice<Exception, Value, Value>(listLike().content(), otherRef.content()) { x, y -> x.equals(y) }
    }

    override fun compare(other: Value): Result<Int> {
        val otherRef =
            ListRef.fromValue(other)
                ?: return ValueError.unsupportedWith(ListData.TYPE, "cmp()", other)
        return compareSlice<Exception, Value, Value>(listLike().content(), otherRef.content()) { x, y -> x.compare(y) }
    }

    override fun at(index: Value, heap: Heap): Result<Value> {
        val i =
            convertIndex(index, listLike().content().size).getOrElse {
                return Result.failure(it)
            }
        return Result.success(listLike().content()[i])
    }

    override fun isIn(other: Value): Result<Boolean> {
        for (x in listLike().content()) {
            if (x.equals(other).getOrElse { return Result.failure(it) }) {
                return Result.success(true)
            }
        }
        return Result.success(false)
    }

    override fun slice(
        start: Value?,
        stop: Value?,
        stride: Value?,
        heap: Heap,
    ): Result<Value> {
        val xs = listLike().content()
        val res = applySlice(xs, start, stop, stride).getOrElse { return Result.failure(it) }
        return Result.success(heap.allocList(res))
    }

    override fun add(rhs: Value, heap: Heap): Result<Value>? {
        val otherRef = ListRef.fromValue(rhs) ?: return null
        return Result.success(heap.allocListConcat(listLike().content(), otherRef.content()))
    }

    override fun mul(rhs: Value, heap: Heap): Result<Value>? {
        val l = rhs.unpackI32() ?: return null
        val content = listLike().content()
        val resultSize = content.size * max(0, l)
        val result = ArrayList<Value>(resultSize)
        for (unused in 0 until l) {
            result.addAll(content)
        }
        return Result.success(heap.allocList(result))
    }

    override fun rmul(lhs: Value, heap: Heap): Result<Value>? = mul(lhs, heap)

    override fun setAt(index: Value, newValue: Value): Result<Unit> {
        val i =
            convertIndex(index, listLike().content().size).getOrElse {
                return Result.failure(it)
            }
        return listLike().setAt(i, newValue)
    }

    override fun typecheckerTy(): Ty = Ty.anyList()

    // fn get_type_starlark_repr() -> Ty
    override fun getTypeStarlarkRepr(): Ty = Ty.anyList()
}

/**
 * Define the mutable list type.
 *
 * Holds the mutable backing content with an iterator guard count.
 */
class ListData(
    /** The data stored by the list. */
    private val content: MutableList<Value> = mutableListOf(),
) : ListLike {
    @PublishedApi
    internal var iterCount: Int = 0

    companion object {
        /** The result of calling `type()` on lists. */
        const val TYPE: String = "list"

        /** Type of list as frozen string value. */
        fun getTypeValueStatic(): String = TYPE

        fun new(content: MutableList<Value>): ListData = ListData(content)

        fun fromValueMut(x: Value): Result<ListData> {
            val gen =
                x.downcastRef<ListGen<*>>()
                    ?: return Result.failure(NotListError(x.getType()))

            val data = gen.data
            if (data is FrozenListData) {
                return Result.failure(ValueError.CannotMutateImmutableValue())
            }
            if (data is ListData) {
                data.checkCanMutate().getOrElse { return Result.failure(it) }
                return Result.success(data)
            }
            return Result.failure(NotListError(x.getType()))
        }

        fun fromValueUncheckedMut(x: Value): ListData {
            val list = x.downcastRef<ListGen<*>>()!!
            val data = list.data as ListData
            check(data.checkCanMutate().isSuccess)
            return data
        }

        fun isListType(x: Any): Boolean =
            x is ListGen<*> && (x.data is ListData || x.data is FrozenListData)
    }

    /** Return an error if there's at least one iterator over the list. */
    fun checkCanMutate(): Result<Unit> {
        if (iterCount != 0) {
            return Result.failure(ValueError.MutationDuringIteration())
        }
        return Result.success(Unit)
    }

    private fun reserveAdditionalSlow(additional: Int, _heap: Heap) {
        val newCap = max(len() + additional, len() * 2)
        // Size of Array is 2 words and size of List is one word,
        // so allocating at least 4 words would not be too large waste.
        // Note Vec allocates 4 by default.
        // Also note Array removes extra capacity on GC.
        val finalCap = max(newCap, 4)
        if (content is ArrayList) {
            content.ensureCapacity(finalCap)
        }
    }

    private fun reserveAdditional(additional: Int, heap: Heap) {
        if (content.size + additional > content.size) {
            reserveAdditionalSlow(additional, heap)
        }
    }

    fun double(heap: Heap) {
        reserveAdditional(len(), heap)
        val snapshot = content.toList()
        content.addAll(snapshot)
    }

    fun extend(iter: Iterable<Value>, heap: Heap) {
        for (v in iter) {
            push(v, heap)
        }
    }

    fun <E : Throwable> tryExtend(iter: Iterator<Result<Value>>, heap: Heap): Result<Unit> {
        for (item in iter) {
            val value = item.getOrElse { return Result.failure(it) }
            push(value, heap)
        }
        return Result.success(Unit)
    }

    fun push(value: Value, heap: Heap) {
        reserveAdditional(1, heap)
        content.add(value)
    }

    fun clear() {
        content.clear()
    }

    fun insert(index: Int, value: Value, heap: Heap) {
        reserveAdditional(1, heap)
        content.add(index, value)
    }

    fun remove(index: Int): Value = content.removeAt(index)

    override fun setAt(i: Int, v: Value): Result<Unit> {
        checkCanMutate().getOrElse { return Result.failure(it) }
        content[i] = v
        return Result.success(Unit)
    }

    fun incIterCount() {
        iterCount++
    }

    fun decIterCount() {
        iterCount--
    }

    /** Obtain the length of the list. */
    fun len(): Int = content.size

    /**
     * List content.
     *
     * Note this operation does not prevent mutation of this list while
     * holding the slice. But such mutation does not violate memory-safety.
     */
    override fun content(): List<Value> = content

    // impl ListLike for ListData
    // In Rust, newIter returns the internal Array value which handles iteration.
    // In Kotlin, ListData uses MutableList, so we handle iteration directly.
    override fun newIter(me: Value): Value {
        incIterCount()
        return me
    }

    override fun iterSizeHint(index: Int): Pair<Int, Int?> {
        check(index <= len())
        val rem = len() - index
        return Pair(rem, rem)
    }

    override fun iterNext(index: Int): Value? {
        if (index >= len()) return null
        return content[index]
    }

    override fun iterStop() {
        decIterCount()
    }

    override fun toString(): String = displayList(content)
}

// impl AllocValue for Vec<V>
fun <T : AllocValue> List<T>.allocValue(heap: Heap): Value =
    heap.allocListIter(this.map { it.allocValue(heap) })

// impl AllocFrozenValue for Vec<V>
fun <T : AllocFrozenValue> List<T>.allocFrozenValue(heap: FrozenHeap): FrozenValue =
    heap.allocList(this.map { it.allocFrozenValue(heap) })

// impl StarlarkTypeRepr for &[V]
inline fun <reified V : StarlarkTypeRepr> sliceStarlarkTypeRepr(): Ty = Ty.anyList()

// impl AllocValue for &[V]
fun <T : AllocValue> Array<T>.allocValue(heap: Heap): Value =
    heap.allocListIter(this.map { it.allocValue(heap) })

// impl AllocFrozenValue for &[V]
fun <T : AllocFrozenValue> Array<T>.allocFrozenValue(heap: FrozenHeap): FrozenValue =
    heap.allocList(this.map { it.allocFrozenValue(heap) })

/**
 * Define the frozen list type.
 *
 * Holds immutable list content after freezing.
 */
class FrozenListData(
    /** The data stored by the tuple. */
    private val content: List<FrozenValue>,
) : ListLike {
    companion object {
        fun new(content: List<FrozenValue>): FrozenListData = FrozenListData(content)

        fun empty(): FrozenListData = FrozenListData(emptyList())

        /** Obtain the [FrozenListData] pointed at by a [FrozenValue]. */
        fun fromFrozenValue(x: FrozenValue): FrozenListData? {
            val gen = x.downcastRef<ListGen<*>>() ?: return null
            return gen.data as? FrozenListData
        }
    }

    fun len(): Int = content.size

    fun contentFrozen(): List<FrozenValue> = content

    // impl ListLike for FrozenListData
    override fun content(): List<Value> = content.map { it.toValue() }

    override fun setAt(i: Int, v: Value): Result<Unit> =
        Result.failure(ValueError.CannotMutateImmutableValue())

    override fun newIter(me: Value): Value = me

    override fun iterSizeHint(index: Int): Pair<Int, Int?> {
        check(index <= len())
        val rem = len() - index
        return Pair(rem, rem)
    }

    override fun iterNext(index: Int): Value? {
        if (index >= len()) return null
        return content[index].toValue()
    }

    override fun iterStop() { /* no-op for frozen lists */ }

    override fun toString(): String = displayList(content.map { it.toValue() })
}

// impl Debug for FrozenListData
fun FrozenListData.debugString(): String = "FrozenList(content=${content()})"

/** Alias is used in `StarlarkDocs` derive. */
typealias FrozenList = ListGen<FrozenListData>

// pub(crate) type List<'v> = ListGen<ListData<'v>>;
typealias MutableStarlarkList = ListGen<ListData>

// pub(crate) static VALUE_EMPTY_FROZEN_LIST
val VALUE_EMPTY_FROZEN_LIST: AllocStaticSimple<FrozenList> =
    AllocStaticSimple.alloc(ListGen(FrozenListData.empty()))

// impl ListGen<FrozenListData> { fn offset_of_content() -> usize }
fun ListGen<FrozenListData>.offsetOfContent(): Int = 0

// Error: Value is not list, value type: `{0}`
private class NotListError(
    type: String,
) : Exception("Value is not list, value type: `$type`")

// pub(crate) trait ListLike<'v>: Debug + Allocative
interface ListLike {
    fun content(): List<Value>

    fun setAt(i: Int, v: Value): Result<Unit>

    fun newIter(me: Value): Value

    fun iterSizeHint(index: Int): Pair<Int, Int?>

    fun iterNext(index: Int): Value?

    fun iterStop()
}

// impl ListLike for ListData
internal class ListDataListLike(
    private val data: ListData,
) : ListLike {
    override fun content(): List<Value> = data.content()

    override fun setAt(i: Int, v: Value): Result<Unit> = data.setAt(i, v)

    override fun newIter(me: Value): Value {
        data.incIterCount()
        return me
    }

    override fun iterSizeHint(index: Int): Pair<Int, Int?> {
        error("Iteration is performed on Array")
    }

    override fun iterNext(index: Int): Value? {
        error("Iteration is performed on Array")
    }

    override fun iterStop() {
        error("Iteration is performed on Array")
    }
}

// impl ListLike for FrozenListData
internal class FrozenListDataListLike(
    private val data: FrozenListData,
) : ListLike {
    override fun content(): List<Value> = data.content().map { it.toValue() }

    override fun setAt(i: Int, v: Value): Result<Unit> =
        Result.failure(ValueError.CannotMutateImmutableValue())

    override fun iterSizeHint(index: Int): Pair<Int, Int?> {
        check(index <= data.len())
        val rem = data.len() - index
        return Pair(rem, rem)
    }

    override fun newIter(me: Value): Value = me

    override fun iterNext(index: Int): Value? {
        if (index >= data.len()) return null
        return data.content()[index].toValue()
    }

    override fun iterStop() { /* no-op for frozen lists */ }
}

// impl Display for ListGen<T>
fun ListGen<*>.display(): String = data.toString()

// pub(crate) fn display_list
internal fun displayList(xs: List<Value>): String =
    buildString {
        append('[')
        xs.forEachIndexed { index, value ->
            if (index > 0) append(", ")
            append(value)
        }
        append(']')
    }

// pub(crate) fn list_methods() -> Option<&'static Methods>
private val LIST_METHODS_STATIC = MethodsStatic()

fun listMethods(): Methods = LIST_METHODS_STATIC.methods(::listMethodsImpl)

// impl Serialize for ListGen<T>
fun ListGen<out ListLike>.serialize(): List<Value> = data.content().toList()

// Heap extensions for list allocation
fun Heap.allocList(content: List<Value>): Value = allocListIter(content)

fun Heap.allocListConcat(a: List<Value>, b: List<Value>): Value = allocListIter(a + b)

// -- isListType check
fun isListType(value: Value): Boolean {
    val gen = value.downcastRef<ListGen<*>>() ?: return false
    return gen.data is ListData || gen.data is FrozenListData
}
